### ISSUE TITLE
Migrating Subscriptions Not Working

### ISSUE THREAD

**Issue by iMattPro** [phpbb-extensions/webpushnotifications#28]
Updating a board from 3.3.12 to 4, the migration of subscription not working.

Yes, the data gets migrated to the phpbb4 tables after uninstalling the extension (after fixing #29). But the user's Subscription's are ignored.

So the user must re-subscribe, but then there are 2 entries for subscriptions in the table for that user (the old migrated entries can not be deleted by unsubscribing).

In this image, ID 1 was migrated from the extension to phpbb4
ID 2 is after hitting the subscribe button again to re-subscribe
<img width="1365" alt="Screenshot 2024-05-13 at 1 16 34 PM" src="https://github.com/phpbb-extensions/webpushnotifications/assets/303711/f191823e-1b90-4015-9de6-b54f7015aa28">

I don't know if either is possible to re-subscribe all existing subscriptions, or if we just don't migrate the data and assume users will just have to re-subscribe after a major 3.3 to 4.x upgrade???

**Comment by rxu** [comment]
Okay, it seems that subscriptions are registered using `U_WEBPUSH_WORKER_URL` which is different between the extension and 4.0 core, so after 3.3 -> 4.0 upgrade we just get new service worker URL unregistered in a browser for webpush and hence unsubscribed. It's like `serviceWorkerUrl: '/app.php/push/worker'` in 3.3 vs `serviceWorkerUrl: '/app.php/user/push/worker'` in 4.0.
Similar for `subscribeUrl` and `unsubscribeUrl` (`user` added in the path for 4.0).

**Comment by rxu** [comment]
Tested and confirmed that after adding `/user` to the 3.3 extension routes all subscriptions migrate correctly. I'm just not sure where `/user` part of the route is coming from in 4.0 as there's no in `ucp.yml` routes.

**Comment by iMattPro** [comment]
@marc1706 Do you have any idea about this?

In the phpbb4 version we have:
```
phpbb_ucp_push_worker_controller:
    path: /push/worker
    defaults: { _controller: phpbb.ucp.controller.webpush:worker }
```

But the resulting url is:
`/app.php/user/push/worker`

Where is `/user` coming from?

**Comment by iMattPro** [comment]
Nevermind. Found it.

```
phpbb_ucp_routing:
    resource: ucp.yml
    prefix: /user
```
I think we just have to make our routes in the extension do the same
