### ISSUE TITLE
not working and not showing up in notifcation to "subscribe"

### ISSUE THREAD

**Issue by AlinGheaja** [phpbb-extensions/webpushnotifications#77]
Hello
i am using SE_GAMERS_DARK (tested with prosilver) and using the latest phpbb, just updated today.
installed and enabled and generated 
![image](https://github.com/user-attachments/assets/7b011be6-d1a3-4564-81d8-fabd5824228a)
on notifications there is no subscribe button and it does not ask for notification premission :(
![test](https://github.com/user-attachments/assets/1c2b564b-054a-4da7-8d2b-8997ff5be279)
on prosilver same
![test2](https://github.com/user-attachments/assets/bb4bebb1-1450-451b-8556-54e4bb0aa7a1)
installed extensions
![image](https://github.com/user-attachments/assets/ffefe71b-08b6-4c7a-bcf2-1e8039afe7f1)

also i tried manualy enabling in chrome notifications from "Ask" to "Allow" but still not working.
what could be the cause of this ?

**Comment by AlinGheaja** [comment]
![image](https://github.com/user-attachments/assets/b0a24e2c-71a3-47b7-b26e-3ccc206d5483)
also this show up

**Comment by iMattPro** [comment]
Please use the support forum for support issues.
https://www.phpbb.com/customise/db/extension/webpushnotifications/support
