### ISSUE TITLE
Fix Errors From Extension Disabling

### ISSUE THREAD

**Issue by iMattPro** [phpbb-extensions/webpushnotifications#9]
Notification methods will persist in the database and/or container, so when disabling the extension, the board can crash. 
![image](https://github.com/phpbb-extensions/webpushnotifications/assets/303711/deae8b6f-3d09-402d-b00b-14ab61dfb98a)

**Comment by iMattPro** [comment]
Will be fixed with https://github.com/phpbb/phpbb/pull/6580

**Comment by rxu** [comment]
And merged already.
